#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# Copyright (C) 2016  Eddie Antonio Santos <easantos@ualberta.ca>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
Some sample crashes from Launchpad.
"""

CRASH_1 = {
    u'project': u'ubuntu',
    u'ApportVersion': u'2.12-0ubuntu3',
    u'ExecutablePath': u'/usr/bin/compiz',
    u'InstallationDate': u'Installed on 2013-02-05 (194 days ago)',
    u'InstallationMedia': u'Ubuntu 12.10 "Quantal Quetzal" - Release amd64 (20121017.5)',
    u'MarkForUpload': u'True',
    u'NonfreeKernelModules': u'nvidia',
    u'Package': u'unity 7.1.0+13.10.20130816.3-0ubuntu1',
    u'ProcCmdline': u'compiz',
    u'ProcEnviron': u' LANGUAGE=en_AU:en\n PATH=(custom, user)\n XDG_RUNTIME_DIR=<set>\n LANG=en_AU.UTF-8\n SHELL=/bin/bash\n',
    u'SegvAnalysis': u' Segfault happened at: 0x7fd116c07289 <_int_free+217>:?mov    0x8(%rdx),%esi\n PC (0x7fd116c07289) ok\n source "0x8(%rdx)" (0x100000007) not located in a known VMA region (needed readable region)!\n destination "%esi" ok\n',
    u'SegvReason': u'reading unknown VMA',
    u'Signal': u'11',
    u'SourcePackage': u'unity',
    u'Title': u'compiz crashed with SIGSEGV in _int_free()',
    u'Uname': u'Linux 3.11.0-2-generic x86_64',
    u'UpgradeStatus': u'Upgraded to saucy on 2013-08-13 (5 days ago)',
    u'UserGroups': u'adm cdrom dip games lpadmin plugdev sambashare sudo vboxusers',
    u'cpu': u'amd64',
    u'database_id': u'launchpad:0001213742',
    u'date': u'2013-08-19T08:58:36',
    u'extra': u'I was searching for an ODT document, and accidentally opened the preview for it, but then when I went the close the preview, Unity froze, and then after about 5 secs, crashed and restarted.\n\nStacktraceTop:  _int_free (av=0x7fd116f47740 <main_arena>, p=0x7d9da60, have_lock=0) at malloc.c:3832\n XDestroyRegion () from /usr/lib/x86_64-linux-gnu/libX11.so.6\n CompRegion::intersects(CompRegion const&) const () from /usr/lib/libcompiz_core.so.ABI-20130125\n unity::UnityScreen::compizDamageNux(CompRegion const&) () from /usr/lib/compiz/libunityshell.so\n unity::UnityScreen::preparePaint(int) () from /usr/lib/compiz/libunityshell.so\n\n',
    u'os': u'Ubuntu 13.10',
    u'os_version': u'Ubuntu 3.11.0-2.5-generic 3.11.0-rc5',
    u'stacktrace': [{u'args': u'av=0x7fd116f47740 <main_arena>, p=0x7d9da60, have_lock=0',
                     u'depth': 0,
                     u'extra': [u'#0  _int_free (av=0x7fd116f47740 <main_arena>, p=0x7d9da60, have_lock=0) at malloc.c:3832',
                                u'        idx = 1',
                                u'        fd = <optimized out>',
                                u'        old = 0xffffffff',
                                u'        old_idx = <optimized out>',
                                u'        size = <optimized out>',
                                u'        fb = 0x7fd116f47750 <main_arena+16>',
                                u'        nextchunk = <optimized out>',
                                u'        nextsize = <optimized out>',
                                u'        nextinuse = <optimized out>',
                                u'        prevsize = <optimized out>',
                                u'        bck = <optimized out>',
                                u'        fwd = <optimized out>',
                                u'        errstr = 0x0',
                                u'        locked = 0',
                                u'        __func__ = "_int_free"'],
                     u'file': u'malloc.c:3832',
                     u'function': u'_int_free'},
                    {u'address': u'0x00007fd1164574c5',
                     u'args': u'r=0x7d9da70',
                     u'depth': 1,
                     u'extra': [u'#1  0x00007fd1164574c5 in XDestroyRegion (r=0x7d9da70) at ../../src/Region.c:288',
                                u'No locals.'],
                     u'file': u'../../src/Region.c:288',
                     u'function': u'XDestroyRegion'},
                    {u'address': u'0x00007fd1174f5c85',
                     u'args': u'',
                     u'depth': 2,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/libcompiz_core.so.ABI-20130125',
                     u'extra': [u'#2  0x00007fd1174f5c85 in CompRegion::intersected(CompRect const&) const () from /tmp/apport_sandbox_HssgYB/usr/lib/libcompiz_core.so.ABI-20130125',
                                u'No symbol table info available.'],
                     u'function': u'CompRegion::intersected(CompRect const&) const'},
                    {u'address': u'0x00007fd0f8432280',
                     u'args': u'',
                     u'depth': 3,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                     u'extra': [u'#3  0x00007fd0f8432280 in unity::UnityScreen::compizDamageNux(CompRegion const&) () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                                u'No symbol table info available.'],
                     u'function': u'unity::UnityScreen::compizDamageNux(CompRegion const&)'},
                    {u'address': u'0x00007fd0f8432884',
                     u'args': u'',
                     u'depth': 4,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                     u'extra': [u'#4  0x00007fd0f8432884 in unity::UnityScreen::preparePaint(int) () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                                u'No symbol table info available.'],
                     u'function': u'unity::UnityScreen::preparePaint(int)'},
                    {u'address': u'0x00007fd110194f25',
                     u'args': u'',
                     u'depth': 5,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
                     u'extra': [u'#5  0x00007fd110194f25 in ?? () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
                                u'No symbol table info available.'],
                     u'function': None},
{u'address': u'0x00000000020a77e0',
 u'args': u'',
 u'depth': 6,
 u'extra': [u'#6  0x00000000020a77e0 in ?? ()',
            u'No symbol table info available.'],
 u'function': None},
{u'address': u'0x0000000002122670',
 u'args': u'',
 u'depth': 7,
 u'extra': [u'#7  0x0000000002122670 in ?? ()',
            u'No symbol table info available.'],
 u'function': None},
{u'address': u'0x0000000007ea80b0',
 u'args': u'',
 u'depth': 8,
 u'extra': [u'#8  0x0000000007ea80b0 in ?? ()',
            u'No symbol table info available.'],
 u'function': None},
{u'address': u'0x00007fd1101966b8',
 u'args': u'',
 u'depth': 9,
 u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
 u'extra': [u'#9  0x00007fd1101966b8 in CompositeScreen::compositingActive() () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
            u'No symbol table info available.'],
 u'function': u'CompositeScreen::compositingActive()'},
{u'address': u'0x0000000000000000',
 u'args': u'',
 u'depth': 10,
 u'extra': [u'#10 0x0000000000000000 in ?? ()',
            u'No symbol table info available.'],
 u'function': None}], u'type': u'Crash'
}

CRASH_2 = {
    u'project': u'ubuntu',
    u'CrashCounter': u'1',
    u'ExecutablePath': u'/usr/lib/gvfs/gvfsd-smb',
    u'NonfreeKernelModules': u'nvidia',
    u'Package': u'gvfs-backends 0.99.6-0ubuntu3',
    u'ProcAttrCurrent': u'unconfined',
    u'ProcCmdline': u'/usr/lib/gvfs/gvfsd-smb --spawner :1.13 /org/gtk/gvfs/exec_spaw/5',
    u'ProcEnviron': u' SHELL=/bin/bash\n PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games\n LANG=en_US.UTF-8\n',
    u'Signal': u'11',
    u'SourcePackage': u'gvfs',
    u'Title': u'gvfsd-smb crashed with SIGSEGV in g_simple_async_result_complete()',
    u'Uname': u'Linux 2.6.27-2-generic i686',
    u'UserGroups': u'adm admin audio cdrom dialout dip floppy fuse lpadmin plugdev pulse pulse-access sambashare scanner users vboxusers video',
    u'cpu': u'i386',
    u'database_id': u'launchpad:0000267589',
    u'extra': u'StacktraceTop:  ?? ()\n ?? () from /usr/lib/libgio-2.0.so.0\n g_simple_async_result_complete ()\n ?? () from /usr/lib/libgio-2.0.so.0\n ?? () from /usr/lib/libgio-2.0.so.0\n\nOccurred while using Rythmbox.  I am sure it is associated w/ the the gvfs mount issue where I cannot mount a network drive. "Error: DBus error org.freedesktop.DBus.Error.InvalidArgs: Mountpoint Already registered Please select another viewer and try again."  I can access my shared files but they show up a missing files in Rhythmbox.  I have been forcing the .gvfs to load my shared files in Nautilus by opening Rhythmbox and then opening the folder in Nautilus.  If open Nautilus before RhythmboxI cannot access the shared files.\n\nBinary package hint: gvfs\n\n',
    u'os': u'Ubuntu 8.10',
    u'stacktrace': [{u'address': u'0x0806110a',
                     u'args': u'',
                     u'depth': 0,
                     u'extra': [u'#0  0x0806110a in ?? ()'],
                     u'function': None},
                    {u'address': u'0xb7b8110f',
                     u'args': u'',
                     u'depth': 1,
                     u'dylib': u'/usr/lib/libgio-2.0.so.0',
                     u'extra': [u'#1  0xb7b8110f in ?? () from /usr/lib/libgio-2.0.so.0'],
                     u'function': None},
                    {u'address': u'0xb7b8ab22',
                     u'args': u'',
                     u'depth': 2,
                     u'extra': [u'#2  0xb7b8ab22 in g_simple_async_result_complete ()',
                                u'   from /usr/lib/libgio-2.0.so.0'],
                     u'function': u'g_simple_async_result_complete'},
                    {u'address': u'0xb7b97ff9',
                     u'args': u'',
                     u'depth': 3,
                     u'dylib': u'/usr/lib/libgio-2.0.so.0',
                     u'extra': [u'#3  0xb7b97ff9 in ?? () from /usr/lib/libgio-2.0.so.0'],
                     u'function': None},
                    {u'address': u'0xb7b6426b',
                     u'args': u'',
                     u'depth': 4,
                     u'dylib': u'/usr/lib/libgio-2.0.so.0',
                     u'extra': [u'#4  0xb7b6426b in ?? () from /usr/lib/libgio-2.0.so.0'],
                     u'function': None},
                    {u'address': u'0xb7a486b1',
                     u'args': u'',
                     u'depth': 5,
                     u'dylib': u'/usr/lib/libglib-2.0.so.0',
                     u'extra': [u'#5  0xb7a486b1 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0'],
                     u'function': u'g_main_context_dispatch'},
                    {u'address': u'0xb7a4bd53',
                     u'args': u'',
                     u'depth': 6,
                     u'dylib': u'/usr/lib/libglib-2.0.so.0',
                     u'extra': [u'#6  0xb7a4bd53 in ?? () from /usr/lib/libglib-2.0.so.0'],
                     u'function': None},
                    {u'address': u'0xb7a4c272',
                     u'args': u'',
                     u'depth': 7,
                     u'dylib': u'/usr/lib/libglib-2.0.so.0',
                     u'extra': [u'#7  0xb7a4c272 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0'],
                     u'function': u'g_main_loop_run'},
                    {u'address': u'0x08051d53',
                     u'args': u'',
                     u'depth': 8,
                     u'extra': [u'#8  0x08051d53 in ?? ()'],
                     u'function': None},
{u'address': u'0x08052025',
 u'args': u'',
 u'depth': 9,
 u'extra': [u'#9  0x08052025 in ?? ()'],
 u'function': None},
{u'address': u'0xb78a9685',
 u'args': u'',
 u'depth': 10,
 u'dylib': u'/lib/tls/i686/cmov/libc.so.6',
 u'extra': [u'#10 0xb78a9685 in __libc_start_main () from /lib/tls/i686/cmov/libc.so.6'],
 u'function': u'__libc_start_main'},
{u'address': u'0x0804df31',
 u'args': u'',
 u'depth': 11,
 u'extra': [u'#11 0x0804df31 in ?? ()'],
 u'function': None}],
u'type': u'Crash'
}

assert CRASH_1 != CRASH_2
