#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# Copyright (C) 2016  Eddie Antonio Santos <easantos@ualberta.ca>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
Some sample crashes from Launchpad.
"""

CRASH_1 = {
    u'type': u'crash',
    u'ApportVersion': u'2.12-0ubuntu3',
    u'ExecutablePath': u'/usr/bin/compiz',
    u'InstallationDate': u'Installed on 2013-02-05 (194 days ago)',
    u'InstallationMedia': u'Ubuntu 12.10 "Quantal Quetzal" - Release amd64 (20121017.5)',
    u'MarkForUpload': u'True',
    u'NonfreeKernelModules': u'nvidia',
    u'Package': u'unity 7.1.0+13.10.20130816.3-0ubuntu1',
    u'ProcCmdline': u'compiz',
    u'ProcEnviron': u' LANGUAGE=en_AU:en\n PATH=(custom, user)\n XDG_RUNTIME_DIR=<set>\n LANG=en_AU.UTF-8\n SHELL=/bin/bash\n',
    u'SegvAnalysis': u' Segfault happened at: 0x7fd116c07289 <_int_free+217>:?mov    0x8(%rdx),%esi\n PC (0x7fd116c07289) ok\n source "0x8(%rdx)" (0x100000007) not located in a known VMA region (needed readable region)!\n destination "%esi" ok\n',
    u'SegvReason': u'reading unknown VMA',
    u'Signal': u'11',
    u'SourcePackage': u'unity',
    u'Title': u'compiz crashed with SIGSEGV in _int_free()',
    u'Uname': u'Linux 3.11.0-2-generic x86_64',
    u'UpgradeStatus': u'Upgraded to saucy on 2013-08-13 (5 days ago)',
    u'UserGroups': u'adm cdrom dip games lpadmin plugdev sambashare sudo vboxusers',
    u'cpu': u'amd64',
    u'database_id': u'launchpad:0001213742',
    u'date': u'2013-08-19T08:58:36',
    u'extra': u'I was searching for an ODT document, and accidentally opened the preview for it, but then when I went the close the preview, Unity froze, and then after about 5 secs, crashed and restarted.\n\nStacktraceTop:  _int_free (av=0x7fd116f47740 <main_arena>, p=0x7d9da60, have_lock=0) at malloc.c:3832\n XDestroyRegion () from /usr/lib/x86_64-linux-gnu/libX11.so.6\n CompRegion::intersects(CompRegion const&) const () from /usr/lib/libcompiz_core.so.ABI-20130125\n unity::UnityScreen::compizDamageNux(CompRegion const&) () from /usr/lib/compiz/libunityshell.so\n unity::UnityScreen::preparePaint(int) () from /usr/lib/compiz/libunityshell.so\n\n',
    u'os': u'Ubuntu 13.10',
    u'os_version': u'Ubuntu 3.11.0-2.5-generic 3.11.0-rc5',
    u'stacktrace': [{u'args': u'av=0x7fd116f47740 <main_arena>, p=0x7d9da60, have_lock=0',
                     u'depth': 0,
                     u'extra': [u'#0  _int_free (av=0x7fd116f47740 <main_arena>, p=0x7d9da60, have_lock=0) at malloc.c:3832',
                                u'        idx = 1',
                                u'        fd = <optimized out>',
                                u'        old = 0xffffffff',
                                u'        old_idx = <optimized out>',
                                u'        size = <optimized out>',
                                u'        fb = 0x7fd116f47750 <main_arena+16>',
                                u'        nextchunk = <optimized out>',
                                u'        nextsize = <optimized out>',
                                u'        nextinuse = <optimized out>',
                                u'        prevsize = <optimized out>',
                                u'        bck = <optimized out>',
                                u'        fwd = <optimized out>',
                                u'        errstr = 0x0',
                                u'        locked = 0',
                                u'        __func__ = "_int_free"'],
                     u'file': u'malloc.c:3832',
                     u'function': u'_int_free'},
                    {u'address': u'0x00007fd1164574c5',
                     u'args': u'r=0x7d9da70',
                     u'depth': 1,
                     u'extra': [u'#1  0x00007fd1164574c5 in XDestroyRegion (r=0x7d9da70) at ../../src/Region.c:288',
                                u'No locals.'],
                     u'file': u'../../src/Region.c:288',
                     u'function': u'XDestroyRegion'},
                    {u'address': u'0x00007fd1174f5c85',
                     u'args': u'',
                     u'depth': 2,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/libcompiz_core.so.ABI-20130125',
                     u'extra': [u'#2  0x00007fd1174f5c85 in CompRegion::intersected(CompRect const&) const () from /tmp/apport_sandbox_HssgYB/usr/lib/libcompiz_core.so.ABI-20130125',
                                u'No symbol table info available.'],
                     u'function': u'CompRegion::intersected(CompRect const&) const'},
                    {u'address': u'0x00007fd0f8432280',
                     u'args': u'',
                     u'depth': 3,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                     u'extra': [u'#3  0x00007fd0f8432280 in unity::UnityScreen::compizDamageNux(CompRegion const&) () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                                u'No symbol table info available.'],
                     u'function': u'unity::UnityScreen::compizDamageNux(CompRegion const&)'},
                    {u'address': u'0x00007fd0f8432884',
                     u'args': u'',
                     u'depth': 4,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                     u'extra': [u'#4  0x00007fd0f8432884 in unity::UnityScreen::preparePaint(int) () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libunityshell.so',
                                u'No symbol table info available.'],
                     u'function': u'unity::UnityScreen::preparePaint(int)'},
                    {u'address': u'0x00007fd110194f25',
                     u'args': u'',
                     u'depth': 5,
                     u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
                     u'extra': [u'#5  0x00007fd110194f25 in ?? () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
                                u'No symbol table info available.'],
                     u'function': None},
{u'address': u'0x00000000020a77e0',
 u'args': u'',
 u'depth': 6,
 u'extra': [u'#6  0x00000000020a77e0 in ?? ()',
            u'No symbol table info available.'],
 u'function': None},
{u'address': u'0x0000000002122670',
 u'args': u'',
 u'depth': 7,
 u'extra': [u'#7  0x0000000002122670 in ?? ()',
            u'No symbol table info available.'],
 u'function': None},
{u'address': u'0x0000000007ea80b0',
 u'args': u'',
 u'depth': 8,
 u'extra': [u'#8  0x0000000007ea80b0 in ?? ()',
            u'No symbol table info available.'],
 u'function': None},
{u'address': u'0x00007fd1101966b8',
 u'args': u'',
 u'depth': 9,
 u'dylib': u'/tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
 u'extra': [u'#9  0x00007fd1101966b8 in CompositeScreen::compositingActive() () from /tmp/apport_sandbox_HssgYB/usr/lib/compiz/libcomposite.so',
            u'No symbol table info available.'],
 u'function': u'CompositeScreen::compositingActive()'},
{u'address': u'0x0000000000000000',
 u'args': u'',
 u'depth': 10,
 u'extra': [u'#10 0x0000000000000000 in ?? ()',
            u'No symbol table info available.'],
 u'function': None}], u'type': u'Crash'
}

CRASH_2 = {
    u'type': u'crash',
    u'ApportVersion': u'2.4-0ubuntu5',
    u'ExecutablePath': u'/usr/lib/i386-linux-gnu/colord/colord-sane',
    u'NonfreeKernelModules': u'nvidia',
    u'Package': u'colord 0.1.21-1',
    u'ProcCmdline': u'/usr/lib/i386-linux-gnu/colord/colord-sane',
    u'ProcEnviron': u' \n',
    u'SegvAnalysis': u' Segfault happened at: 0xb54dca12:?mov    (%edx),%esi\n PC (0xb54dca12) ok\n source "(%edx)" (0x625f6d65) not located in a known VMA region (needed readable region)!\n destination "%esi" ok\n',
    u'SegvReason': u'reading unknown VMA',
    u'Signal': u'11',
    u'SourcePackage': u'colord',
    u'Title': u'colord-sane crashed with SIGSEGV',
    u'Uname': u'Linux 3.5.0-6-generic i686',
    u'UpgradeStatus': u'No upgrade log present (probably fresh install)',
    u'UserGroups': u'scanner',
    u'cpu': u'i386',
    u'database_id': u'launchpad:0001029264',
    u'date': u'2012-07-26T07:20:50',
    u'extra': u'crash at login time on quantal i386 logged as gnome-classic with nvidia-current graphic\n\nStacktraceTop:  ?? () from /lib/i386-linux-gnu/libdbus-1.so.3\n ?? () from /lib/i386-linux-gnu/libdbus-1.so.3\n ?? () from /lib/i386-linux-gnu/libdbus-1.so.3\n ?? () from /lib/i386-linux-gnu/libdbus-1.so.3\n ?? () from /lib/i386-linux-gnu/libdbus-1.so.3\n\n',
    u'os': u'Ubuntu 12.10',
    u'os_version': u'Ubuntu 3.5.0-6.6-generic 3.5.0',
    u'stacktrace': [{u'args': u'link=0x9992508, before_this_link=0x625f6d65, list=0x998f6fc',
                     u'depth': 0,
                     u'extra': [u'#0  link_before (link=0x9992508, before_this_link=0x625f6d65, list=0x998f6fc) at ../../dbus/dbus-list.c:120',
                                u'No locals.'],
                     u'file': u'../../dbus/dbus-list.c:120',
                     u'function': u'link_before'},
                    {u'args': u'list=0x998f6fc, link=0x9992508',
                     u'depth': 1,
                     u'extra': [u'#1  _dbus_list_prepend_link (list=0x998f6fc, link=0x9992508) at ../../dbus/dbus-list.c:313',
                                u'No locals.'],
                     u'file': u'../../dbus/dbus-list.c:313',
                     u'function': u'_dbus_list_prepend_link'},
                    {u'address': u'0xb54dca6a',
                     u'args': u'list=0x998f6fc, link=0x9992508',
                     u'depth': 2,
                     u'extra': [u'#2  0xb54dca6a in _dbus_list_append_link (list=0x998f6fc, link=0x9992508) at ../../dbus/dbus-list.c:295',
                                u'No locals.'],
                     u'file': u'../../dbus/dbus-list.c:295',
                     u'function': u'_dbus_list_append_link'},
                    {u'address': u'0xb54cb568',
                     u'args': u'message=0x998f6a0, link=0x9992508',
                     u'depth': 3,
                     u'extra': [u'#3  0xb54cb568 in _dbus_message_add_counter_link (message=0x998f6a0, link=0x9992508) at ../../dbus/dbus-message.c:249',
                                u'No locals.'],
                     u'file': u'../../dbus/dbus-message.c:249',
                     u'function': u'_dbus_message_add_counter_link'},
                    {u'address': u'0xb54cb606',
                     u'args': u'message=0x998f6a0, counter=0x9997090',
                     u'depth': 4,
                     u'extra': [u'#4  0xb54cb606 in _dbus_message_add_counter (message=0x998f6a0, counter=0x9997090) at ../../dbus/dbus-message.c:278',
                                u'        link = 0x9992508'],
                     u'file': u'../../dbus/dbus-message.c:278',
                     u'function': u'_dbus_message_add_counter'},
                    {u'address': u'0xb54d8be7',
                     u'args': u'transport=0x9996d30',
                     u'depth': 5,
                     u'extra': [u'#5  0xb54d8be7 in _dbus_transport_queue_messages (transport=0x9996d30) at ../../dbus/dbus-transport.c:1138',
                                u'        message = <optimized out>',
                                u'        link = 0x99924f0',
                                u'        status = <optimized out>'],
                     u'file': u'../../dbus/dbus-transport.c:1138',
                     u'function': u'_dbus_transport_queue_messages'},
                    {u'address': u'0xb54d9827',
                     u'args': u'transport=0x9996d30',
                     u'depth': 6,
                     u'extra': [u'#6  0xb54d9827 in do_reading (transport=0x9996d30) at ../../dbus/dbus-transport-socket.c:851',
                                u'        buffer = 0x9996e24',
                                u'        bytes_read = 260',
                                u'        total = 260',
                                u'        oom = <optimized out>'],
                     u'file': u'../../dbus/dbus-transport-socket.c:851',
                     u'function': u'do_reading'},
{u'address': u'0xb54d9f17',
 u'args': u'transport=0x9996d30',
 u'depth': 7,
 u'extra': [u'#7  0xb54d9f17 in do_reading (transport=0x9996d30) at ../../dbus/dbus-transport-socket.c:706',
            u'        socket_transport = 0x9996d30'],
 u'file': u'../../dbus/dbus-transport-socket.c:706',
 u'function': u'do_reading'},
{u'args': u'transport=0x9996d30, flags=6, timeout_milliseconds=25000',
 u'depth': 8,
 u'extra': [u'#8  socket_do_iteration (transport=0x9996d30, flags=6, timeout_milliseconds=25000) at ../../dbus/dbus-transport-socket.c:1162',
            u'        need_read = 1',
            u'        need_write = 0',
            u'        authentication_completed = 0',
            u'        socket_transport = 0x9996d30',
            u'        poll_fd = {fd = 13, events = 1, revents = 1}',
            u'        poll_res = <optimized out>',
            u'        poll_timeout = <optimized out>'],
 u'file': u'../../dbus/dbus-transport-socket.c:1162',
 u'function': u'socket_do_iteration'},
{u'address': u'0xb54d890d',
 u'args': u'transport=0x9996d30, flags=6, timeout_milliseconds=25000',
 u'depth': 9,
 u'extra': [u'#9  0xb54d890d in _dbus_transport_do_iteration (transport=0x9996d30, flags=6, timeout_milliseconds=25000) at ../../dbus/dbus-transport.c:974',
            u'No locals.'],
 u'file': u'../../dbus/dbus-transport.c:974',
 u'function': u'_dbus_transport_do_iteration'},
{u'address': u'0xb54c0614',
 u'args': u'connection=0x99971a8, pending=0x9996c58, flags=6, timeout_milliseconds=25000',
 u'depth': 10,
 u'extra': [u'#10 0xb54c0614 in _dbus_connection_do_iteration_unlocked (connection=0x99971a8, pending=0x9996c58, flags=6, timeout_milliseconds=25000) at ../../dbus/dbus-connection.c:1215',
            u'No locals.'],
 u'file': u'../../dbus/dbus-connection.c:1215',
 u'function': u'_dbus_connection_do_iteration_unlocked'},
{u'address': u'0xb54c1b14',
 u'args': u'pending=0x9996c58',
 u'depth': 11,
 u'extra': [u'#11 0xb54c1b14 in _dbus_connection_block_pending_call (pending=0x9996c58) at ../../dbus/dbus-connection.c:2404',
            u'        start_tv_sec = 39',
            u'        start_tv_usec = 526607',
            u'        tv_sec = 161049688',
            u'        tv_usec = -1079918980',
            u'        status = <optimized out>',
            u'        connection = 0x99971a8',
            u'        client_serial = 1',
            u'        timeout = 0x9997260',
            u'        timeout_milliseconds = 25000',
            u'        elapsed_milliseconds = <optimized out>'],
 u'file': u'../../dbus/dbus-connection.c:2404',
 u'function': u'_dbus_connection_block_pending_call'},
{u'address': u'0xb54d237f',
 u'args': u'pending=0x9996c58',
 u'depth': 12,
 u'extra': [u'#12 0xb54d237f in dbus_pending_call_block (pending=0x9996c58) at ../../dbus/dbus-pending-call.c:705',
            u'        __FUNCTION__ = "dbus_pending_call_block"'],
 u'file': u'../../dbus/dbus-pending-call.c:705',
 u'function': u'dbus_pending_call_block'},
{u'address': u'0xb54c0f4b',
 u'args': u'connection=0x99971a8, message=0x998fa00, timeout_milliseconds=-1, error=0xb4cb116c',
 u'depth': 13,
 u'extra': [u'#13 0xb54c0f4b in dbus_connection_send_with_reply_and_block (connection=0x99971a8, message=0x998fa00, timeout_milliseconds=-1, error=0xb4cb116c) at ../../dbus/dbus-connection.c:3515',
            u'        reply = <optimized out>',
            u'        pending = 0x9996c58',
            u'        __FUNCTION__ = "dbus_connection_send_with_reply_and_block"'],
 u'file': u'../../dbus/dbus-connection.c:3515',
 u'function': u'dbus_connection_send_with_reply_and_block'},
{u'address': u'0xb54bba34',
 u'args': u'connection=0x99971a8, error=0xb4cb116c',
 u'depth': 14,
 u'extra': [u'#14 0xb54bba34 in dbus_bus_register (connection=0x99971a8, error=0xb4cb116c) at ../../dbus/dbus-bus.c:698',
            u'        message = <optimized out>',
            u'        reply = <optimized out>',
            u'        name = <optimized out>',
            u'        bd = <optimized out>',
            u'        retval = 0',
            u'        __FUNCTION__ = "dbus_bus_register"'],
 u'file': u'../../dbus/dbus-bus.c:698',
 u'function': u'dbus_bus_register'},
{u'address': u'0xb54bbd5f',
 u'args': u'type=DBUS_BUS_SYSTEM, private=0, error=0xb4cb116c',
 u'depth': 15,
 u'extra': [u'#15 0xb54bbd5f in internal_bus_get (type=DBUS_BUS_SYSTEM, private=0, error=0xb4cb116c) at ../../dbus/dbus-bus.c:491',
            u'        address = <optimized out>',
            u'        connection = 0x99971a8',
            u'        bd = <optimized out>',
            u'        address_type = DBUS_BUS_SYSTEM',
            u'        __FUNCTION__ = "internal_bus_get"'],
 u'file': u'../../dbus/dbus-bus.c:491',
 u'function': u'internal_bus_get'},
{u'address': u'0xb4c9166c',
 u'args': u'',
 u'depth': 16,
 u'dylib': u'/tmp/tmpoqDoof/usr/lib/sane/libsane-hpaio.so.1',
 u'extra': [u'#16 0xb4c9166c in ?? () from /tmp/tmpoqDoof/usr/lib/sane/libsane-hpaio.so.1',
            u'No symbol table info available.'],
 u'function': None},
{u'address': u'0xb4c8da77',
 u'args': u'',
 u'depth': 17,
 u'dylib': u'/tmp/tmpoqDoof/usr/lib/sane/libsane-hpaio.so.1',
 u'extra': [u'#17 0xb4c8da77 in sane_hpaio_init () from /tmp/tmpoqDoof/usr/lib/sane/libsane-hpaio.so.1',
            u'No symbol table info available.'],
 u'function': u'sane_hpaio_init'},
{u'address': u'0xb777b492',
 u'args': u'be=be@entry=0x995a700',
 u'depth': 18,
 u'extra': [u'#18 0xb777b492 in init (be=be@entry=0x995a700) at dll.c:612',
            u'        status = <optimized out>',
            u'        version = -1216876556'],
 u'file': u'dll.c:612',
 u'function': u'init'},
{u'address': u'0xb777bf40',
 u'args': u'device_list=device_list@entry=0xbfa1c0ec, local_only=local_only@entry=1',
 u'depth': 19,
 u'extra': [u'#19 0xb777bf40 in sane_dll_get_devices (device_list=device_list@entry=0xbfa1c0ec, local_only=local_only@entry=1) at dll.c:1053',
            u'        be_list = 0xb55421d8',
            u'        be = 0x995a700',
            u'        status = <optimized out>',
            u'        full_name = <optimized out>',
            u'        i = <optimized out>',
            u'        num_devs = <optimized out>',
            u'        len = <optimized out>'],
 u'file': u'dll.c:1053',
 u'function': u'sane_dll_get_devices'},
{u'address': u'0xb77795f3',
 u'args': u'dl=dl@entry=0xbfa1c0ec, local=local@entry=1',
 u'depth': 20,
 u'extra': [u'#20 0xb77795f3 in sane_get_devices (dl=dl@entry=0xbfa1c0ec, local=local@entry=1) at dll-s.c:17',
            u'No locals.'],
 u'file': u'dll-s.c:17',
 u'function': u'sane_get_devices'},
{u'address': u'0x08049dc9',
 u'args': u'priv=priv@entry=0x994d6f0',
 u'depth': 21,
 u'extra': [u'#21 0x08049dc9 in cd_sane_client_refresh (priv=priv@entry=0x994d6f0) at cd-main.c:303',
            u'        tmp = <optimized out>',
            u'        device_list = 0x0',
            u'        i = <optimized out>',
            u'        status = <optimized out>'],
 u'file': u'cd-main.c:303',
 u'function': u'cd_sane_client_refresh'},
{u'address': u'0x0804a1c5',
 u'args': u'source_object=0x9954990, res=0x9957950, user_data=user_data@entry=0x994d6f0',
 u'depth': 22,
 u'extra': [u'#22 0x0804a1c5 in cd_main_colord_connect_cb (source_object=0x9954990, res=0x9957950, user_data=user_data@entry=0x994d6f0) at cd-main.c:446',
            u'        priv = 0x994d6f0',
            u'        ret = <optimized out>',
            u'        error = 0x0'],
 u'file': u'cd-main.c:446',
 u'function': u'cd_main_colord_connect_cb'},
{u'address': u'0xb767b1f0',
 u'args': u'simple=0x9957950',
 u'depth': 23,
 u'extra': [u'#23 0xb767b1f0 in g_simple_async_result_complete (simple=0x9957950) at /build/buildd/glib2.0-2.33.6/./gio/gsimpleasyncresult.c:775',
            u'        current_source = <optimized out>',
            u'        current_context = <optimized out>',
            u'        __PRETTY_FUNCTION__ = "g_simple_async_result_complete"'],
 u'file': u'/build/buildd/glib2.0-2.33.6/./gio/gsimpleasyncresult.c:775',
 u'function': u'g_simple_async_result_complete'},
{u'address': u'0xb767b31c',
 u'args': u'data=data@entry=0x9957950',
 u'depth': 24,
 u'extra': [u'#24 0xb767b31c in complete_in_idle_cb (data=data@entry=0x9957950) at /build/buildd/glib2.0-2.33.6/./gio/gsimpleasyncresult.c:787',
            u'        simple = <optimized out>'],
 u'file': u'/build/buildd/glib2.0-2.33.6/./gio/gsimpleasyncresult.c:787',
 u'function': u'complete_in_idle_cb'},
{u'address': u'0xb75071c0',
 u'args': u'source=source@entry=0x995b368, callback=0xb767b2f0 <complete_in_idle_cb>, user_data=0x9957950',
 u'depth': 25,
 u'extra': [u'#25 0xb75071c0 in g_idle_dispatch (source=source@entry=0x995b368, callback=0xb767b2f0 <complete_in_idle_cb>, user_data=0x9957950) at /build/buildd/glib2.0-2.33.6/./glib/gmain.c:4781',
            u'No locals.'],
 u'file': u'/build/buildd/glib2.0-2.33.6/./glib/gmain.c:4781',
 u'function': u'g_idle_dispatch'},
{u'address': u'0xb7509ef3',
 u'args': u'context=0x994d738',
 u'depth': 26,
 u'extra': [u'#26 0xb7509ef3 in g_main_dispatch (context=0x994d738) at /build/buildd/glib2.0-2.33.6/./glib/gmain.c:2691',
            u'        dispatch = 0xb75071a0 <g_idle_dispatch>',
            u'        was_in_call = 0',
            u'        user_data = 0x9957950',
            u'        callback = 0xb767b2f0 <complete_in_idle_cb>',
            u'        cb_funcs = 0xb75bd4f8',
            u'        cb_data = 0x995c6a8',
            u'        current_source_link = {data = 0x995b368, next = 0x0}',
            u'        need_destroy = <optimized out>',
            u'        source = 0x995b368',
            u'        current = 0x994c8a0',
            u'        i = <optimized out>'],
 u'file': u'/build/buildd/glib2.0-2.33.6/./glib/gmain.c:2691',
 u'function': u'g_main_dispatch'},
{u'args': u'context=context@entry=0x994d738',
 u'depth': 27,
 u'extra': [u'#27 g_main_context_dispatch (context=context@entry=0x994d738) at /build/buildd/glib2.0-2.33.6/./glib/gmain.c:3195',
            u'No locals.'],
 u'file': u'/build/buildd/glib2.0-2.33.6/./glib/gmain.c:3195',
 u'function': u'g_main_context_dispatch'},
{u'address': u'0xb750a290',
 u'args': u'context=0x994d738, block=block@entry=1, dispatch=dispatch@entry=1, self=<error reading variable: Unhandled dwarf expression opcode 0xfa>',
 u'depth': 28,
 u'extra': [u'#28 0xb750a290 in g_main_context_iterate (context=0x994d738, block=block@entry=1, dispatch=dispatch@entry=1, self=<error reading variable: Unhandled dwarf expression opcode 0xfa>) at /build/buildd/glib2.0-2.33.6/./glib/gmain.c:3266',
            u'        max_priority = 0',
            u'        timeout = 0',
            u'        some_ready = 1',
            u'        nfds = 2',
            u'        allocated_nfds = <optimized out>',
            u'        fds = <optimized out>'],
 u'file': u'/build/buildd/glib2.0-2.33.6/./glib/gmain.c:3266',
 u'function': u'g_main_context_iterate'},
{u'address': u'0xb750a6eb',
 u'args': u'loop=0x994d6d0',
 u'depth': 29,
 u'extra': [u'#29 0xb750a6eb in g_main_loop_run (loop=0x994d6d0) at /build/buildd/glib2.0-2.33.6/./glib/gmain.c:3460',
            u'        __PRETTY_FUNCTION__ = "g_main_loop_run"'],
 u'file': u'/build/buildd/glib2.0-2.33.6/./glib/gmain.c:3460',
 u'function': u'g_main_loop_run'},
{u'address': u'0x080497d4',
 u'args': u'argc=1, argv=0xbfa1c3f4',
 u'depth': 30,
 u'extra': [u'#30 0x080497d4 in main (argc=1, argv=0xbfa1c3f4) at cd-main.c:617',
            u'        priv = 0x994d6f0',
            u'        immediate_exit = 0',
            u'        timed_exit = 0',
            u'        error = 0x0',
            u'        context = <optimized out>',
            u'        retval = 1',
            u'        options = {{long_name = 0x804a609 "timed-exit", short_name = 0 \'\\000\', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0xbfa1c2e0, description = 0x804a614 "Exit after a small delay", arg_description = 0x0}, {long_name = 0x804a62d "immediate-exit", short_name = 0 \'\\000\', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0xbfa1c2dc, description = 0x804a6e4 "Exit after the engine has loaded", arg_description = 0x0}, {long_name = 0x0, short_name = 0 \'\\000\', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}'],
 u'file': u'cd-main.c:617',
 u'function': u'main'}],
u'type': u'Crash'
}

assert CRASH_1 != CRASH_2
